./teste < dot/bipartite_graphs/0_3.dot >> res/0_3_emp.dot
./teste < dot/bipartite_graphs/3_5.dot >> res/3_5_emp.dot
./teste < dot/bipartite_graphs/4_3.dot >> res/4_3_emp.dot
./teste < dot/bipartite_graphs/4_4.dot >> res/4_4_emp.dot
./teste < dot/bipartite_graphs/6_7.dot >> res/6_7_emp.dot
./teste < dot/bipartite_graphs/8_1.dot >> res/8_1_emp.dot
./teste < dot/bipartite_graphs/8_3.dot >> res/8_3_emp.dot
./teste < dot/bipartite_graphs/10_12.dot >> res/10_12_emp.dot
./teste < dot/bipartite_graphs/14_12.dot >> res/14_12_emp.dot
./teste < dot/bipartite_graphs/15_16.dot >> res/15_16_emp.dot
./teste < dot/bipartite_graphs/16_9.dot >> res/16_9_emp.dot
./teste < dot/bipartite_graphs/16_16.dot >> res/16_16_emp.dot 
./teste < dot/bipartite_graphs/25_24.dot >> res/25_24_emp.dot
./teste < dot/bipartite_graphs/28_19.dot >> res/28_19_emp.dot
./teste < dot/bipartite_graphs/28_32.dot >> res/28_32_emp.dot 
./teste < dot/bipartite_graphs/34_57.dot >> res/34_57_emp.dot
./teste < dot/bipartite_graphs/45_36.dot >> res/45_36_emp.dot 
./teste < dot/bipartite_graphs/58_38.dot >> res/58_38_emp.dot
./teste < dot/bipartite_graphs/61_52.dot >> res/61_52_emp.dot
./teste < dot/bipartite_graphs/77_75.dot >> res/77_75_emp.dot 
./teste < dot/bipartite_graphs/117_77.dot >> res/117_77_emp.dot
./teste < dot/bipartite_graphs/146_180.dot >> res/146_180_emp.dot
./teste < dot/bipartite_graphs/181_230.dot >> res/181_230_emp.dot 
./teste < dot/bipartite_graphs/349_300.dot >> res/349_300_emp.dot 
./teste < dot/bipartite_graphs/425_359.dot >> res/425_359_emp.dot
./teste < dot/bipartite_graphs/3MaximumMatching.dot >> res/3MaximumMatching_emp.dot 
./teste < dot/bipartite_graphs/3MaximumMatching2.dot >> res/3MaximumMatching2_emp.dot 
./teste < dot/bipartite_graphs/4MaximumMatching.dot >> res/4MaximumMatching_emp.dot
./teste < dot/bipartite_graphs/4MaximumMatching2.dot >> res/4MaximumMatching2_emp.dot
./teste < dot/bipartite_graphs/5MaximumMatching.dot >> res/5MaximumMatching_emp.dot
./teste < dot/bipartite_graphs/5MaximumMatching2.dot >> res/5MaximumMatching2_emp.dot
./teste < dot/bipartite_graphs/5Mlanguages.dot  >> res/5Mlanguages_emp.dot
./teste < dot/bipartite_graphs/6MaximumMatching.dot  >> res/6MaximumMatching_emp.dot
./teste < dot/bipartite_graphs/6MaximumMatching2.dot  >> res/6MaximumMatching2_emp.dot
./teste < dot/bipartite_graphs/7MaximumMatching.dot >> res/7MaximumMatching_emp.dot
./teste < dot/bipartite_graphs/26MaximumMatching.dot  >> res/26MaximumMatching_emp.dot
