#!/bin/bash

valgrind ./teste < dot/4pathCordal.dot
valgrind ./teste < dot/5pathCordal.dot
valgrind ./teste < dot/5starCordal.dot
valgrind ./teste < dot/32fanCordal.dot
valgrind ./teste < dot/32poleCordal.dot
valgrind ./teste < dot/a.dot
valgrind ./teste < dot/b.dot
valgrind ./teste < dot/borboletaCordal.dot
valgrind ./teste < dot/c.dot
valgrind ./teste < dot/chordal.dot
valgrind ./teste < dot/cidades.dot
valgrind ./teste < dot/cordal.dot
valgrind ./teste < dot/cordal1.dot
valgrind ./teste < dot/cordalBull.dot
valgrind ./teste < dot/cordalCasa.dot
valgrind ./teste < dot/cordalTriangulo.dot
valgrind ./teste < dot/cricketCordal.dot
valgrind ./teste < dot/d.dot
valgrind ./teste < dot/dartoCordal.dot
valgrind ./teste < dot/diamanteCordal.dot
valgrind ./teste < dot/emacs24-dep.dot
valgrind ./teste < dot/garfoCordal.dot
valgrind ./teste < dot/jssCordal.dot
valgrind ./teste < dot/k6.dot
valgrind ./teste < dot/kiteCordal.dot
valgrind ./teste < dot/large.dot
valgrind ./teste < dot/naoCordal.dot
valgrind ./teste < dot/paises.dot
valgrind ./teste < dot/pawCordal.dot
valgrind ./teste < dot/pentagramaCordal.dot
valgrind ./teste < dot/pirulitoCordal.dot
valgrind ./teste < dot/simple.dot
valgrind ./teste < dot/teste.dot
valgrind ./teste < dot/testedir.dot
